export const kcommWid: string;
export const footernUpart: string;
export const commWid: string;
export const nftblock: string;
export const abpTit: string;
export const nftb: string;
export const awra: string;
export const nsplitLine: string;
export const aline: string;
